from fpdf import FPDF
from datetime import datetime

# ── LIGHT THEME — High Contrast ──────────────────────────────
COLOR_BG       = (255, 255, 255)     # White page
COLOR_CARD     = (245, 246, 250)     # Light gray card
COLOR_TEXT     = (20, 20, 30)        # Near-black text
COLOR_MUTED    = (100, 105, 120)     # Gray secondary text
COLOR_ACCENT   = (15, 90, 200)      # Deep blue accent
COLOR_SEC      = (100, 60, 190)     # Purple accent
COLOR_BORDER   = (210, 215, 225)    # Light borders
COLOR_SUCCESS  = (16, 140, 70)      # Green
COLOR_DANGER   = (200, 40, 40)      # Red
COLOR_WARNING  = (200, 130, 0)      # Amber
COLOR_WATERMARK = (230, 232, 238)   # Very light gray for watermark

SEVERITY_COLORS = {
    "Critical": (140, 50, 210),
    "High":     (200, 40, 40),
    "Medium":   (200, 130, 0),
    "Low":      (30, 100, 210),
    "Info":     (100, 115, 135),
}

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info"]


class PDFReport(FPDF):
    """Verse Scan — Professional Security Assessment PDF Report (Light Theme)"""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    # ── Sanitization ──────────────────────────────────────────
    def sanitize(self, text):
        if text is None:
            return ""
        return str(text).encode('latin-1', 'replace').decode('latin-1')

    # ── Header ────────────────────────────────────────────────
    def header(self):
        # White background
        self.set_fill_color(*COLOR_BG)
        self.rect(0, 0, 210, 297, 'F')

        # Skip header on cover page (page 1)
        if self.page_no() == 1:
            self._draw_watermark()
            return

        # Draw watermark first (behind content)
        self._draw_watermark()

        # Top header bar — white with bottom border
        self.set_fill_color(*COLOR_BG)
        self.rect(0, 0, 210, 16, 'F')

        # Bottom accent line
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(0, 16, 210, 0.6, 'F')

        # Brand text
        self.set_font('Arial', 'B', 11)
        self.set_text_color(*COLOR_ACCENT)
        self.set_xy(10, 3)
        self.cell(0, 10, 'VERSE SCAN', 0, 0, 'L')

        self.set_y(22)

    # ── Footer ────────────────────────────────────────────────
    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-14)
        self.set_fill_color(*COLOR_BORDER)
        self.rect(10, 282, 190, 0.3, 'F')
        self.set_font('Arial', '', 7)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 10, f'Generated by Verse Scan  |  Page {self.page_no()}', 0, 0, 'C')

    # ── Watermark ─────────────────────────────────────────────
    def _draw_watermark(self):
        """Draw diagonal 'HACK VERSE' watermark across the page."""
        self.set_font('Arial', 'B', 52)
        self.set_text_color(*COLOR_WATERMARK)
        # Draw rotated watermark text
        self.rotate(35, 105, 148)
        self.set_xy(20, 130)
        self.cell(0, 20, 'HACK VERSE', 0, 0, 'C')
        self.rotate(0)  # reset rotation

        self.rotate(35, 105, 200)
        self.set_xy(20, 190)
        self.cell(0, 20, 'HACK VERSE', 0, 0, 'C')
        self.rotate(0)  # reset rotation

    # ── Drawing Helpers ───────────────────────────────────────
    def _draw_section_title(self, number, title):
        """Draw a numbered section heading with accent underline."""
        self._ensure_space(22)
        self.ln(6)
        self.set_font('Arial', 'B', 15)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(0, 10, self.sanitize(f"{number}.  {title}"), 0, 1, 'L')
        # Accent underline
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(10, self.get_y(), 50, 0.7, 'F')
        self.set_fill_color(*COLOR_BORDER)
        self.rect(60, self.get_y(), 140, 0.3, 'F')
        self.ln(6)

    def _draw_label_value(self, label, value, indent=10):
        """Draw a label: value pair."""
        self.set_x(indent)
        self.set_font('Arial', 'B', 9)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(42, 7, self.sanitize(label), 0, 0)
        self.set_font('Arial', '', 9)
        self.set_text_color(*COLOR_TEXT)
        val = self.sanitize(value)
        if len(val) > 90:
            self.ln(7)
            self.set_x(indent + 42)
            self.multi_cell(0, 5, val)
        else:
            self.cell(0, 7, val, 0, 1)

    def _draw_card_rect(self, x, y, w, h):
        """Draw a light card background with border."""
        self.set_fill_color(*COLOR_CARD)
        self.rect(x, y, w, h, 'F')
        self.set_draw_color(*COLOR_BORDER)
        self.rect(x, y, w, h, 'D')

    def _ensure_space(self, needed):
        """Add a page break if not enough vertical space remains."""
        if self.get_y() + needed > 270:
            self.add_page()

    # ── Risk Score ────────────────────────────────────────────
    @staticmethod
    def compute_risk_score(findings):
        weights = {"Critical": 4, "High": 3, "Medium": 2, "Low": 1, "Info": 0}
        if not findings:
            return 0.0
        total_weight = sum(weights.get(f.get("severity", "Info"), 0) for f in findings)
        # Scale: max possible per finding is 4, so normalize
        max_possible = len(findings) * 4
        if max_possible == 0:
            return 0.0
        score = (total_weight / max_possible) * 10.0
        return min(round(score, 1), 10.0)

    @staticmethod
    def _risk_label(score):
        if score == 0:
            return "No Risk  -  Clean Scan"
        if score < 3:
            return "Low Risk  -  Minor Issues"
        if score < 5:
            return "Moderate Risk  -  Attention Needed"
        if score < 7:
            return "High Risk  -  Remediation Required"
        return "Critical Risk  -  Immediate Action Required"

    @staticmethod
    def _risk_color(score):
        if score < 3:
            return (16, 140, 70)     # Green
        if score < 5:
            return (30, 100, 210)    # Blue
        if score < 7:
            return (200, 130, 0)     # Amber
        return (200, 40, 40)         # Red

    # ── Severity Counts ───────────────────────────────────────
    @staticmethod
    def _count_severities(findings):
        counts = {s: 0 for s in SEVERITY_ORDER}
        for f in findings:
            sev = f.get('severity', 'Info')
            if sev in counts:
                counts[sev] += 1
        return counts

    # ══════════════════════════════════════════════════════════
    #  GENERATE — Main Entry Point
    # ══════════════════════════════════════════════════════════
    def generate(self, scan_data, filename="report.pdf"):
        findings = scan_data.get('findings', [])
        target = scan_data.get('target', scan_data.get('target_url', 'Unknown'))
        crawled_urls = scan_data.get('crawled_urls', [])
        risk_score = scan_data.get('risk_score', self.compute_risk_score(findings))
        counts = self._count_severities(findings)
        total_findings = len(findings)

        # ── Page 1: Cover ─────────────────────────────────────
        self._generate_cover(target, risk_score, total_findings)

        # ── Section 1: Executive Summary ──────────────────────
        self.add_page()
        self._generate_executive_summary(findings, counts, risk_score, total_findings)

        # ── Section 2: Scan Configuration ─────────────────────
        self._generate_scan_config(scan_data, target, crawled_urls)

        # ── Section 3: Risk Assessment ────────────────────────
        self._generate_risk_assessment(counts, risk_score, total_findings)

        # ── Section 4: Detailed Findings ──────────────────────
        self._generate_findings(findings, counts)

        # ── Section 5: Appendix — Crawled URLs ────────────────
        if crawled_urls:
            self._generate_crawled_urls(crawled_urls)

        self.output(filename)
        return filename

    # ══════════════════════════════════════════════════════════
    #  COVER PAGE
    # ══════════════════════════════════════════════════════════
    def _generate_cover(self, target, risk_score, total_findings):
        self.add_page()

        # Top accent bar
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(0, 0, 210, 4, 'F')

        # Brand name
        self.set_y(55)
        self.set_font('Arial', 'B', 40)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(0, 18, 'VERSE SCAN', 0, 1, 'C')

        # Accent line under brand
        self.set_fill_color(*COLOR_SEC)
        self.rect(65, self.get_y() + 3, 80, 1.2, 'F')

        # Subtitle
        self.ln(10)
        self.set_font('Arial', '', 14)
        self.set_text_color(*COLOR_TEXT)
        self.cell(0, 8, 'Security Assessment Report', 0, 1, 'C')

        # Divider
        self.ln(22)
        self.set_fill_color(*COLOR_BORDER)
        self.rect(30, self.get_y(), 150, 0.4, 'F')
        self.ln(18)

        # Target URL card
        card_y = self.get_y()
        self._draw_card_rect(25, card_y, 160, 35)
        self.set_xy(25, card_y + 5)
        self.set_font('Arial', '', 9)
        self.set_text_color(*COLOR_MUTED)
        self.cell(160, 6, 'TARGET', 0, 1, 'C')
        self.set_x(25)
        self.set_font('Arial', 'B', 13)
        self.set_text_color(*COLOR_TEXT)
        self.cell(160, 10, self.sanitize(str(target)[:80]), 0, 1, 'C')

        self.ln(22)

        # Stats row — 3 cards
        stats_y = self.get_y()
        col_w = 53
        stats = [
            ("RISK SCORE", f"{risk_score}/10", self._risk_color(risk_score)),
            ("FINDINGS", str(total_findings), COLOR_ACCENT),
            ("DATE", datetime.now().strftime('%Y-%m-%d'), COLOR_SEC),
        ]
        for idx, (label, value, color) in enumerate(stats):
            x = 25 + idx * col_w
            self._draw_card_rect(x, stats_y, col_w - 3, 30)
            self.set_xy(x, stats_y + 5)
            self.set_font('Arial', '', 8)
            self.set_text_color(*COLOR_MUTED)
            self.cell(col_w - 3, 5, label, 0, 2, 'C')
            self.set_font('Arial', 'B', 18)
            self.set_text_color(*color)
            self.cell(col_w - 3, 12, value, 0, 0, 'C')

        # Bottom accent bar
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(0, 293, 210, 4, 'F')

    # ══════════════════════════════════════════════════════════
    #  1. EXECUTIVE SUMMARY
    # ══════════════════════════════════════════════════════════
    def _generate_executive_summary(self, findings, counts, risk_score, total_findings):
        self._draw_section_title("1", "Executive Summary")

        # Risk verdict card
        label = self._risk_label(risk_score)
        color = self._risk_color(risk_score)
        card_y = self.get_y()
        self._draw_card_rect(10, card_y, 190, 24)

        # Color strip on left
        self.set_fill_color(*color)
        self.rect(10, card_y, 3, 24, 'F')

        self.set_xy(18, card_y + 4)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(*color)
        self.cell(0, 8, self.sanitize(label), 0, 1)
        self.set_x(18)
        self.set_font('Arial', '', 9)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 6, f"Risk Score: {risk_score}/10  |  Total Findings: {total_findings}", 0, 1)
        self.ln(6)

        # Severity distribution grid
        self._draw_severity_grid(counts)
        self.ln(6)

        # Top findings summary (up to 3 Critical/High)
        critical_high = [f for f in findings if f.get('severity') in ('Critical', 'High')]
        if critical_high:
            self._ensure_space(30)
            self.set_font('Arial', 'B', 10)
            self.set_text_color(*COLOR_TEXT)
            self.cell(0, 8, 'Key Findings Requiring Attention:', 0, 1)
            self.ln(2)
            for f in critical_high[:3]:
                self._ensure_space(14)
                sev = f.get('severity', 'Info')
                sev_color = SEVERITY_COLORS.get(sev, COLOR_MUTED)
                self.set_x(14)
                # Bullet with color
                self.set_fill_color(*sev_color)
                self.rect(14, self.get_y() + 1.5, 2.5, 2.5, 'F')
                self.set_x(20)
                self.set_font('Arial', 'B', 9)
                self.set_text_color(*sev_color)
                self.cell(0, 5, self.sanitize(f"[{sev}]  {f.get('name', 'Unknown')}"), 0, 1)
                self.set_x(20)
                self.set_font('Arial', '', 8)
                self.set_text_color(*COLOR_MUTED)
                url_text = f.get('url', '')
                if len(url_text) > 80:
                    url_text = url_text[:77] + '...'
                self.cell(0, 5, self.sanitize(url_text), 0, 1)
                self.ln(1)

    def _draw_severity_grid(self, counts):
        """Draw the 5-column severity count grid."""
        start_y = self.get_y()
        col_w = 37
        margin_x = 10

        for idx, sev in enumerate(SEVERITY_ORDER):
            x = margin_x + idx * col_w
            color = SEVERITY_COLORS.get(sev, COLOR_MUTED)

            # Card
            self._draw_card_rect(x, start_y, col_w - 2, 28)

            # Top color accent strip
            self.set_fill_color(*color)
            self.rect(x, start_y, col_w - 2, 2.5, 'F')

            # Severity label
            self.set_xy(x, start_y + 6)
            self.set_font('Arial', 'B', 8)
            self.set_text_color(*color)
            self.cell(col_w - 2, 5, sev.upper(), 0, 2, 'C')

            # Count
            self.set_font('Arial', 'B', 16)
            self.set_text_color(*COLOR_TEXT)
            self.cell(col_w - 2, 10, str(counts.get(sev, 0)), 0, 0, 'C')

        self.set_y(start_y + 32)

    # ══════════════════════════════════════════════════════════
    #  2. SCAN CONFIGURATION
    # ══════════════════════════════════════════════════════════
    def _generate_scan_config(self, scan_data, target, crawled_urls):
        self._ensure_space(80)
        self._draw_section_title("2", "Scan Configuration")

        started = scan_data.get('started_at', scan_data.get('created_at', 'N/A'))
        completed = scan_data.get('completed_at', 'N/A')
        status = scan_data.get('status', 'Unknown')

        duration_str = 'N/A'
        try:
            if started and completed and started != 'N/A' and completed != 'N/A':
                start_str = str(started).replace('Z', '+00:00').split('+')[0].split('.')[0]
                end_str = str(completed).replace('Z', '+00:00').split('+')[0].split('.')[0]
                fmt = '%Y-%m-%dT%H:%M:%S'
                s = datetime.strptime(start_str, fmt)
                e = datetime.strptime(end_str, fmt)
                delta = e - s
                mins, secs = divmod(int(delta.total_seconds()), 60)
                duration_str = f"{mins}m {secs}s" if mins else f"{secs}s"
        except Exception:
            pass

        crawled_count = scan_data.get('crawled_count', len(crawled_urls))

        card_y = self.get_y()
        self._draw_card_rect(10, card_y, 190, 52)
        self.set_y(card_y + 5)

        self._draw_label_value("Target URL:", str(target), 15)
        self._draw_label_value("Status:", status, 15)
        self._draw_label_value("Started At:", str(started), 15)
        self._draw_label_value("Completed At:", str(completed), 15)
        self._draw_label_value("Duration:", duration_str, 15)
        self._draw_label_value("Pages Crawled:", str(crawled_count), 15)

        self.set_y(card_y + 56)

    # ══════════════════════════════════════════════════════════
    #  3. RISK ASSESSMENT
    # ══════════════════════════════════════════════════════════
    def _generate_risk_assessment(self, counts, risk_score, total_findings):
        self._ensure_space(90)
        self._draw_section_title("3", "Risk Assessment")

        # Score card
        card_y = self.get_y()
        self._draw_card_rect(10, card_y, 190, 40)
        self.set_xy(15, card_y + 5)

        self.set_font('Arial', 'B', 11)
        self.set_text_color(*COLOR_TEXT)
        self.cell(0, 8, 'Overall Risk Score', 0, 1)

        # Progress bar background
        bar_y = self.get_y() + 2
        self.set_fill_color(*COLOR_BORDER)
        self.rect(15, bar_y, 160, 10, 'F')

        # Progress bar fill
        bar_width = max(risk_score / 10.0 * 160, 0)
        color = self._risk_color(risk_score)
        self.set_fill_color(*color)
        if bar_width > 0:
            self.rect(15, bar_y, bar_width, 10, 'F')

        # Score text
        self.set_xy(15, bar_y + 1)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(255, 255, 255)
        self.cell(160, 8, f'{risk_score} / 10', 0, 0, 'C')

        self.set_y(card_y + 44)

        # Severity breakdown table
        self._ensure_space(55)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(*COLOR_TEXT)
        self.cell(0, 8, 'Severity Breakdown', 0, 1)
        self.ln(2)

        # Table header
        table_y = self.get_y()
        self.set_fill_color(*COLOR_ACCENT)
        self.rect(10, table_y, 190, 9, 'F')
        self.set_xy(10, table_y)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(255, 255, 255)
        self.cell(50, 9, '  SEVERITY', 0, 0)
        self.cell(35, 9, 'COUNT', 0, 0, 'C')
        self.cell(45, 9, 'PERCENTAGE', 0, 0, 'C')
        self.cell(60, 9, 'RISK WEIGHT', 0, 1, 'C')

        # Table rows
        weights_map = {"Critical": 4, "High": 3, "Medium": 2, "Low": 1, "Info": 0}
        for row_idx, sev in enumerate(SEVERITY_ORDER):
            count = counts.get(sev, 0)
            pct = f"{(count / max(total_findings, 1)) * 100:.1f}%" if total_findings else "0%"
            weight = f"{count * weights_map[sev]}"

            row_y = self.get_y()
            # Alternating row background
            if row_idx % 2 == 0:
                self.set_fill_color(*COLOR_CARD)
            else:
                self.set_fill_color(*COLOR_BG)
            self.rect(10, row_y, 190, 8, 'F')
            # Bottom border
            self.set_draw_color(*COLOR_BORDER)
            self.line(10, row_y + 8, 200, row_y + 8)

            sev_color = SEVERITY_COLORS.get(sev, COLOR_MUTED)
            self.set_xy(10, row_y)

            # Color dot
            self.set_fill_color(*sev_color)
            self.rect(13, row_y + 2.5, 3, 3, 'F')

            self.set_font('Arial', 'B', 8)
            self.set_text_color(*sev_color)
            self.cell(50, 8, f'      {sev}', 0, 0)
            self.set_text_color(*COLOR_TEXT)
            self.set_font('Arial', '', 8)
            self.cell(35, 8, str(count), 0, 0, 'C')
            self.cell(45, 8, pct, 0, 0, 'C')
            self.set_text_color(*COLOR_MUTED)
            self.cell(60, 8, weight, 0, 1, 'C')

        self.ln(6)

        # Verdict
        self._ensure_space(18)
        label = self._risk_label(risk_score)
        color = self._risk_color(risk_score)
        self.set_font('Arial', 'I', 9)
        self.set_text_color(*color)
        self.multi_cell(0, 5, self.sanitize(
            f'Assessment Verdict: {label}. '
            f'The risk score is calculated using a weighted formula '
            f'(Critical x4, High x3, Medium x2, Low x1) normalized across {total_findings} finding(s).'
        ))
        self.ln(5)

    # ══════════════════════════════════════════════════════════
    #  4. DETAILED FINDINGS
    # ══════════════════════════════════════════════════════════
    def _generate_findings(self, findings, counts):
        self.add_page()
        self._draw_section_title("4", "Detailed Findings")

        if not findings:
            self._ensure_space(30)
            card_y = self.get_y()
            self._draw_card_rect(10, card_y, 190, 25)
            self.set_fill_color(*COLOR_SUCCESS)
            self.rect(10, card_y, 3, 25, 'F')
            self.set_xy(18, card_y + 5)
            self.set_font('Arial', 'B', 12)
            self.set_text_color(*COLOR_SUCCESS)
            self.cell(0, 8, 'No Vulnerabilities Detected', 0, 1)
            self.set_x(18)
            self.set_font('Arial', '', 9)
            self.set_text_color(*COLOR_MUTED)
            self.cell(0, 6, 'The scan completed without discovering any security issues.', 0, 1)
            return

        finding_num = 0
        for sev in SEVERITY_ORDER:
            sev_findings = [f for f in findings if f.get('severity', 'Info') == sev]
            if not sev_findings:
                continue

            # Severity group header
            self._ensure_space(20)
            sev_color = SEVERITY_COLORS.get(sev, COLOR_MUTED)

            self.set_fill_color(*sev_color)
            self.rect(10, self.get_y(), 190, 9, 'F')
            self.set_xy(14, self.get_y())
            self.set_font('Arial', 'B', 9)
            self.set_text_color(255, 255, 255)
            self.cell(0, 9, self.sanitize(f"{sev.upper()}  ({len(sev_findings)})"), 0, 1)
            self.ln(4)

            for finding in sev_findings:
                finding_num += 1
                self._draw_finding_card(finding, finding_num, sev_color)

    def _draw_finding_card(self, finding, number, sev_color):
        """Render a single finding as a styled card."""
        self._ensure_space(55)

        card_y = self.get_y()

        # Card background
        self._draw_card_rect(10, card_y, 190, 50)

        # Left accent strip
        self.set_fill_color(*sev_color)
        self.rect(10, card_y, 3, 50, 'F')

        # ── Row 1: Number + Name + CWE ──
        self.set_xy(17, card_y + 4)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(*COLOR_TEXT)
        name = finding.get('name', finding.get('type', 'Vulnerability'))
        cwe = finding.get('cwe', '')
        title_text = f"#{number}  {name}"
        self.cell(0, 6, self.sanitize(title_text), 0, 0)

        if cwe:
            self.set_font('Arial', '', 8)
            self.set_text_color(*COLOR_MUTED)
            self.cell(0, 6, f"  {cwe}", 0, 0)
        self.ln(7)

        # ── Row 2: URL ──
        self.set_x(17)
        self.set_font('Arial', '', 8)
        self.set_text_color(*COLOR_ACCENT)
        url_text = self.sanitize(finding.get('url', 'N/A'))
        if len(url_text) > 100:
            url_text = url_text[:97] + '...'
        self.cell(0, 5, url_text, 0, 1)

        # ── Row 3: Param + Payload ──
        param = finding.get('param', finding.get('parameter', ''))
        payload = finding.get('payload', '')
        if param or payload:
            self.set_x(17)
            self.set_font('Arial', '', 7)
            self.set_text_color(*COLOR_WARNING)
            parts = []
            if param:
                parts.append(f"Param: {param}")
            if payload:
                parts.append(f"Payload: {payload}")
            detail_text = self.sanitize("  |  ".join(parts))
            if len(detail_text) > 110:
                detail_text = detail_text[:107] + '...'
            self.cell(0, 5, detail_text, 0, 1)

        # ── Row 4: Description ──
        desc = finding.get('description', '')
        if desc:
            self.set_x(17)
            self.set_font('Arial', '', 8)
            self.set_text_color(*COLOR_MUTED)
            desc_text = self.sanitize(desc)
            if len(desc_text) > 180:
                desc_text = desc_text[:177] + '...'
            self.multi_cell(178, 4, desc_text)

        # ── Row 5: Remediation ──
        remediation = finding.get('remediation', '')
        if remediation:
            self.set_x(17)
            self.set_font('Arial', 'B', 7)
            self.set_text_color(*COLOR_SUCCESS)
            self.cell(12, 5, 'FIX:', 0, 0)
            self.set_font('Arial', '', 7)
            self.set_text_color(30, 100, 50)
            rem_text = self.sanitize(remediation)
            if len(rem_text) > 140:
                rem_text = rem_text[:137] + '...'
            self.cell(0, 5, rem_text, 0, 1)

        # Ensure past the card
        min_y = card_y + 52
        if self.get_y() < min_y:
            self.set_y(min_y)
        self.ln(3)

    # ══════════════════════════════════════════════════════════
    #  5. APPENDIX — CRAWLED URLS
    # ══════════════════════════════════════════════════════════
    def _generate_crawled_urls(self, crawled_urls):
        self.add_page()
        self._draw_section_title("5", "Appendix: Crawled URLs")

        self.set_font('Arial', '', 9)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 6, self.sanitize(f"Total URLs discovered: {len(crawled_urls)}"), 0, 1)
        self.ln(4)

        for idx, url in enumerate(crawled_urls, 1):
            self._ensure_space(7)

            row_y = self.get_y()
            if idx % 2 == 0:
                self.set_fill_color(*COLOR_CARD)
                self.rect(10, row_y, 190, 6, 'F')

            self.set_font('Arial', '', 7)
            self.set_text_color(*COLOR_MUTED)
            self.cell(10, 6, f"{idx:>3}.", 0, 0)
            self.set_text_color(*COLOR_ACCENT)
            url_text = self.sanitize(str(url))
            if len(url_text) > 120:
                url_text = url_text[:117] + '...'
            self.cell(0, 6, url_text, 0, 1)
